#!/usr/bin/env python3
"""
Diagnose why FreqTrade isn't closing trades
"""

print("=" * 80)
print("FREQTRADE EXIT SIGNAL DIAGNOSIS")
print("=" * 80)

print("\n🔍 ANALYZING FREQTRADE INTEGRATION:")
print("-" * 60)

print("\n1. HOW FREQTRADE EXITS WORK:")
print("   - populate_exit_trend() sets exit_long=1 or exit_short=1")
print("   - custom_exit() returns exit reason string")
print("   - FreqTrade checks these every candle")

print("\n2. CURRENT IMPLEMENTATION (SqueezeFlowFreqAI.py):")
print("   ✅ Has populate_exit_trend() method")
print("   ❌ Only triggers on signal_action == 'CLOSE'")
print("   ❌ No custom_exit() method for dynamic exits")

print("\n3. THE PROBLEM:")
print("   - Strategy Runner generates signals with action='LONG' or 'SHORT'")
print("   - It NEVER generates action='CLOSE' signals!")
print("   - Phase 5 exit logic runs in Strategy Runner, not FreqTrade")
print("   - FreqTrade never receives exit signals")

print("\n4. ROOT CAUSE ANALYSIS:")
print("   STRATEGY RUNNER (services/strategy_runner.py):")
print("   - Runs Phase 1-5 analysis")
print("   - Phase 5 determines should_exit=True")
print("   - BUT it doesn't publish 'CLOSE' signals to Redis!")
print("   - Only publishes entry signals (LONG/SHORT)")
print()
print("   FREQTRADE (SqueezeFlowFreqAI.py):")
print("   - Reads signals from Redis")
print("   - Waits for action='CLOSE' which never comes")
print("   - populate_exit_trend() never sets exit_long=1")

print("\n5. WHY TRADES DON'T CLOSE:")
print("   ✅ Strategy Runner detects exit conditions")
print("   ❌ But doesn't publish CLOSE signals to Redis")
print("   ❌ FreqTrade never receives exit instructions")
print("   ❌ Positions stay open forever")

print("\n" + "=" * 80)
print("THE MISSING LINK")
print("=" * 80)

print("\nIn services/strategy_runner.py, when should_exit=True:")
print("Currently: Does nothing with exit signals")
print("SHOULD: Publish CLOSE signal to Redis")
print()
print("Example fix needed:")
print("if exit_result.get('should_exit'):")
print("    signal = {")
print("        'action': 'CLOSE',")
print("        'symbol': symbol,")
print("        'signal_id': position.get('id'),")
print("        'reason': exit_result.get('exit_reasoning'),")
print("        'timestamp': datetime.now()")
print("    }")
print("    redis_client.publish('signals', signal)")

print("\n" + "=" * 80)
print("ALTERNATIVE: IMPLEMENT custom_exit()")
print("=" * 80)

print("\nFreqTrade can also use custom_exit() method:")
print("- Runs on every candle for open trades")
print("- Can check conditions directly")
print("- Returns exit reason string to trigger exit")
print()
print("But this would duplicate Phase 5 logic in FreqTrade")
print("Better to fix the signal flow")

print("\n" + "=" * 80)
print("COMPLETE DIAGNOSIS")
print("=" * 80)

print("\n🔴 CRITICAL ISSUE FOUND:")
print("Strategy Runner's Phase 5 exit logic is NOT connected to FreqTrade!")
print()
print("1. Backtest: Uses Phase 5 directly ✅")
print("2. Strategy Runner: Runs Phase 5 but doesn't publish CLOSE signals ❌")
print("3. FreqTrade: Waits for CLOSE signals that never come ❌")
print()
print("This explains why BOTH live trades (BTC & ETH) aren't closing!")
print("The exit logic works but isn't wired to FreqTrade.")