influxdb:
  database: significant_trades
  host: localhost
  password: password123
  port: 8086
  username: squeezeflow
logging:
  file: data/logs/squeezeflow.log
  level: DEBUG
  rotation:
    count: 5
    enabled: true
    size: 100MB
notifications:
  enabled: false
  telegram:
    bot_token: ''
    chat_id: ''
redis:
  db: 0
  host: localhost
  port: 6379
system:
  debug: true
  dry_run: true
  mode: development
