enabled: false
features:
  order_flow: true
  sentiment: false
  technical_indicators: true
  volume_profile: true
model_type: lightgbm
training:
  lookback_days: 90
  retrain_frequency: weekly
  validation_split: 0.2
