filters:
  min_volume_24h: 100000000
  trending_only: false
  volatility_filter: true
squeeze_detection:
  confirmation_candles: 2
  cvd_threshold: 1000000
  price_momentum_threshold: 0.005
  volume_threshold: 2.0
symbols:
- BTC/USDT
- ETH/USDT
timeframes:
- 1m
- 5m
- 15m
