# SqueezeFlow Strategy Runner Service Configuration
# This file provides production-ready defaults for the Strategy Runner Service

# Service execution settings
run_interval_seconds: 60
max_symbols_per_cycle: 5
enable_parallel_processing: true

# Data settings
data_lookback_hours: 48  # Full 48 hours - data is now complete after backfill
min_data_points: 500     # Restored original requirement
default_timeframe: "5m"

# Redis settings (Docker will override via environment variables)
redis_host: "localhost"
redis_port: 6379
redis_db: 0
redis_signal_ttl: 600  # 10 minutes (to handle FreqTrade timing)
redis_key_prefix: "squeezeflow"

# InfluxDB settings (Docker will override via environment variables)
influx_host: "localhost"
influx_port: 8086
influx_database: "significant_trades"
influx_username: ""
influx_password: ""

# Signal generation settings
publish_to_redis: true
store_in_influxdb: true
signal_retention_hours: 24

# Strategy settings
strategy_name: "SqueezeFlowStrategy"
enable_position_sizing: true
enable_leverage_scaling: true

# Risk management
max_concurrent_signals: 5
signal_cooldown_minutes: 2

# Monitoring and logging
log_level: "INFO"
enable_performance_monitoring: true
health_check_interval: 30

# Error handling
max_retries: 3
retry_delay_seconds: 5
graceful_shutdown_timeout: 30