apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://aggr-influx:8086
    user: ""
    password: ""
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      dbName: significant_trades
      httpMode: POST
      timeInterval: "5s"
    secureJsonData:
      password: ""